CREATE TABLE TASKS (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    DESCRIPTION TEXT,
    STATUS VARCHAR(20),
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);