"""change description to string

Revision ID: 7d00fee24de3
Revises: b69689851503
Create Date: 2026-02-18 15:56:15.332228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d00fee24de3'
down_revision: Union[str, None] = 'b69689851503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
