"""soft delete

Revision ID: d3bc9a626301
Revises: 68550bc4cadd
Create Date: 2026-03-19 16:08:11.027447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bc9a626301'
down_revision: Union[str, None] = '68550bc4cadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('isDeleted', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('deletedAt', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deletedAt')
    op.drop_column('tasks', 'isDeleted')
    # ### end Alembic commands ###
